config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
  	resources :comments
  end

  root 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.create(params[:comment].permit(:comment))

      if @comment.save
        redirect_to post_path(@post)
      else
        render 'new'
      end
    end

    def destroy
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
      @comment.destroy

      redirect_to post_path(@post)
    end

    def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    end

    def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.update(params[:comment].permit(:comment))
      redirect_to post_path(@post)
    else
      render 'edit'
    end
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only:[:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @post = Post.all.order("created_at DESC")
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

      if @post.save
        redirect_to @post
      else
        render 'new'
      end
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'new'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

private

def post_params
  params.require(:post).permit(:title, :content)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.comment %></p>
<p class="buttons">
<%= link_to "Delete Reply", [comment.post, comment], method: :delete, data: { confirm: "Are you sure?" } %><%= link_to "Edit", edit_post_comment_path(comment.post, comment) %>
 </p>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
  <p><%= f.input :comment %></p>
  <p><%= f.submit %></p>
  <% end %>
  

app/views/comments/edit.html.erb
<div class="container">
    <div class="jumbotron">
    <h3>Edit Reply</h3>
    <%= simple_form_for ([@post, @comment]) do |f| %>
    <%= f.input :comment %>
    <%= f.submit %>
    <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum Rails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
          <div class="header">
                <div class="navbar navbar-default">
                          <div class="navbar-header col-lg-6 col-md-8 col-sm-6 col-xs-8"><p class="navbar-brand"><%= link_to "Forum Rails", root_path %></p></div>
                          <div class="col-lg-6 col-md-4 col-sm-6 col-xs-4">
                            <ul class="nav navbar-nav navbar-right">
                              <p class="buttons">
                                <% if user_signed_in? %>
                                <%= link_to 'New Post', new_post_path %>
                                <% else %>
                                <%= link_to 'Sign In', new_user_session_path %>
                                <%= link_to 'Sign Up', new_user_registration_path %>
                                <% end %>
                              </p>
                            </ul>
                          </div>
                </div>
          </div>
  </div>


  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

            <%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
      <%= f.input :title %>
      <%= f.input :content %>
      <%= f.submit %>
    <% end %>

app/views/posts/edit.html.erb
<div class="container">
  <div class="jumbotron">
    <h3>Edit Posts</h3>

    <%= render 'form' %>

    <%= link_to 'Cancel', post_path %>
    </div>
</div>

app/views/posts/index.html.erb
<div class="container">
      <div class="jumbotron">
          <% @post.each do |post| %>
            <h2 id="link"><%= link_to post.title, post %>
              <p style="font-size: 0.4em; margin-top: 5px; margin-bottom: 40px;">Published at <%= post.user.email %> </p>
              <p style="font-size: 0.4em; margin-bottom: 40px;"></p>
              <% end %>
              <br>
        </div>


<!-- SECTION FOOTER -->
      <footer>
            <hr></hr>
            <p style="font-size: 1em;"class="text-center">written and coded by <a href="#" class="name" style="font-size: 1em;">Aldo P.</a></p>
      </footer>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="jumbotron">
    <h3>New Posts</h3>

    <%= render 'form' %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
    <div class="jumbotron">
        <h3><%= @post.title %></h3>
        <p style="font-size: 1em;"><%= @post.content %></p>
        <p class="buttons">
          <%= link_to 'Edit', edit_post_path(@post) %><%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %><%= link_to 'Home', root_path %>
        </p>
        <div class="jumbotron">
        <h2><%= @post.comments.count %> Comments </h2>
        <%= render @post.comments %>
        <h2> Add a comment </h2>
        <%= render "comments/form" %>



        </div>
    </div>
</div>